data_dir: data
metadata_dir: metadata
metadata_id_col: AriaId
intermediate_files_dir: intermediate
logs_dir: logs
log_level: DEBUG
sequential: false
features:
  - melodic
#  - harmonic
#  - texture
split: true