data_dir: data
metadata_dir: metadata
metadata_id_col: AriaId
intermediate_files_dir: intermediate
parallel: true
max_processes: 10
read_log:
  file_path: logs/read.log
  level: DEBUG
write_log:
  file_path: logs/write.log
  level: INFO
features:
  - file_name
  - librettist
  - harmony
  # - ambitus
  # - density
  # - interval
  # - key
  - lyrics
  - prefix
  # - scale
  - scoring
  - tempo
  - composer
split_keywords:  # Used to split the possible layers present depending on the instrument name
  - woodwind
  - brass
  - wind
