data_dir: data
metadata_dir: metadata
metadata_id_col: AriaId
intermediate_files_dir: intermediate
parallel: false
max_processes: 10
features:
  - file_name
  - metadata
  - harmony
  - ambitus
  - density
  - interval
  - key
  - lyrics
  - metadata
  - prefix
  - scale
  - scoring
  - tempo
  - text
split_keywords:  # Used to split the possible layers present depending on the instrument name
  - woodwind
  - brass
  - wind