# Directory to save the logs files, level for logging in the console (console_level) and
# in the log file (file_level)
log:
  file_path: ./musif.log
  file_level: DEBUG
  console_level: ERROR

# Flag to determine whether to delete rows associated to files containing errors (whose
# FileNames bust be contained in a './errors.csv' file) or not
delete_files: False

# Flag to determine whether delete rows associated to files that do not have harmonic
# annotations (and
# hence, no harmonic analysis) or not
delete_files_without_harmony: False

# Flag to determine if multiple voices (e.g. duetos and trios) sould be merge into
# the same column (SoundVoice_*), calculating averages, min or max of both values 
merge_voices: True

# Flag to determine if keys, keys modulatory and degrees columns should be grouped per type
# For instance, about the keys:
# * IV, II, and VI will be merged into the SD group (subdominant)
# * iv, ii, will be merged into the sd group (subdominant)
# * I and i will be merged into the T group (tonic)
# * III and vi will be merged into the rel group (relative)
# 
# The degrees will be merged into [Doubly] Augmented, [Doubly] Diminished, Natural, No
# Natural. This applies to both raw and percentage degree features.
grouped: False

# Flag to determine if Intrumentation column should be disgregated in several columns
# (Presence_of_*) having a value of 1 if instrument is present, 0 otherwise.
# see also `delete_presence` option
separate_intrumentation_column: False

# Specify the instruments whose features will be kept even if they are merged with the option
# `grouped`
# Matching is case-sensitive
instruments_to_keep: []
  # Possible values are from abbreviations from musif.musicxml.constants.SOUND_TO_ABBREVIATION
  # Note that if an abbreviation is not available, the full instrument name is used
  # Example:
  # - vnI
  # - bs
 
# Specify the instuments whose features will be deleted
# i.e. 
# * features containing 'Part' + <inst> will be deleted
# * features containing <inst> + '_' will be deleted
# Matching is case-sensitive
instruments_to_delete: []
  # Possible values are from abbreviations from musif.musicxml.constants.SOUND_TO_ABBREVIATION
  # Note that if an abbreviation is not available, the full instrument name is used
  # First letter is always capitalized
  # Example:
  # - Ob
  # - Cor
  # - Bn
  # - Va
  # - Eh
  # - Tbn
  # - TbI
  # - Timp
  # - Tr
  # - TrI
  # - BsI
  # - BsII
  # - VeI
  # - VeII
  # - CI
  # - CiII
  # - CiI

# Rows having more than this percentage of NaN will be deleted
# value null (or None) means "keep all"
max_nan_rows: null

# Columns having more than this percentage of NaN will be deleted (applied after
# `max_nan_rows`)
# value null (or None) means "keep all"
max_nan_columns: null

# Columns containing these substrings will have nan values replaced with 0
# Applied after `max_nan_rows` and `max_nan_columns`
# Matching is case-sensitive
replace_nans: []
  # Example of values (but any substring can be used):
  # - Interval
  # - Degree
  # - Harmony

# Columns ending with any of these strings will be deleted
# Matching is case-sensitive
columns_endswith: []
  # example of values (but any other suffix can be used)
  # - _HighestNote
  # - _LowestNote
  # - _Notes
  # - _SoundingMeasures
  # - _Syllables
  # - _NumberOfFilteredParts
  # - NumberOfParts
  # - _NotesMean
  # - Librettist
  # - _LargestIntervalAsc
  # - _LargestIntervalAll
  # - _LargestIntervalDesc
  # - _NotesMean
  # - 'Semitones_Sum'    
  # - _MeanInterval'

# Columns starting with any of these strings will be deleted
# Matching is case-sensitive
columns_startswith: []
  # example of values (but any other prefix can be used)
  # - FamilyWw
  # - FamilyBr
  # - FamilyGen
  # - FamilyGen
  # - FamilyPerc
  # - EndOfThemeA
  # - NumberOfBeats
  # - SoundVoice_Dyn

# Columns containing any of these strings will be deleted
# Matching is case-sensitive
columns_contain: []
  # example of values (but any other substring can be used)
  # - _Count
  # - _SoundingMeasuresMean
  # - _SmallestSemitones
  # - _SmallestAbsolute
  # - _SmallestInterval
  # - Bn
  # - VnII
  # - VnIII
  # - VnIV
  # - Vc
  # - Cl
  # - Tpt
  # - Hn
  # - Fl

# Columns exactly matching any of these strings will be deleted
# Matching is case-sensitive
columns_match: []
  # example of values (but any column can be used)
  # - Presence_of_vn
  # - Presence_of_bs
  # - Presence_of_vc
  # - Presence_of_va
