data_dir: data
metadata_dir: metadata
metadata_id_col: AriaId
intermediate_files_dir: intermediate
parallel: false
max_processes: 10
logs_dir: logs
log_level: ERROR
features:
  - file_name
  - metadata
  - harmony
  - tempo
  - key
  - scoring
  - prefix
  - text
split_keywords:
  - woodwind
  - brass
  - wind