data_dir: ../tests/data/static/features/Did03M-Son_regina-1730-Sarro[1.05][0006].xml
musescore_dir:
metadata_dir: ../metadata
metadata_id_col: AriaId
parallel: false
expand_repeats: false
max_processes: 8
log:
  file_path: ./musif.log
  file_level: DEBUG
  console_level: WARNING
features:
  - scoring
  - file_name
  - themeA
  - core
  - ambitus
  - interval
  - tempo
  - key
  - dynamics
  - rhythm
split_keywords:  # Used to split the possible layers present depending on the instrument name
  - woodwind
  - brass
  - wind
parts_filter:
  - vnI
  - vnII
  - va
  - bs
  - sop
  - ten
  - alt
  - bar
  - bass
  - bbar
