metadata_dir: ./metadata
metadata_id_col: AriaId
data_dir: arias
musescore_dir:
expand_repeats: false
parallel: false
max_processes: 8
log:
  file_path: logs/musif.log
  file_level: DEBUG
  console_level: INFO
features:
  - scoring
  - file_name
  - metadata
  - themeA
  - core
  - composer
  - librettist
  - key
  - tempo
  # - interval
  # - ambitus # Melody Values report depends on both ambitus and interval to work!
  - scale_relative
  # - harmony
  # - density
  # - texture
  # - lyrics
  # - scale
  # - dynamics

split_keywords:  # Used to split the possible layers present depending on the instrument name
  - woodwind
  - brass
  - wind

parts_filter:
  - vnI
  - obI
  - sop
  # - ten
  # - vnII
  # - va
  # - bs
  # - alt
  # - bar
  # - bass
  # - bbar
