data_dir: ../data
musescore_dir: ../data
metadata_dir: metadata
metadata_id_col: AriaId
intermediate_files_dir: intermediate
parallel: true
max_processes: 10
read_log:
  file_path: logs/read.log
  level: INFO
write_log:
  file_path: logs/write.log
  level: INFO
features:
  - core
  - custom.core_mscx
  - scoring
  - custom.file_name
  - scale
  - custom.scale_relative
  - custom.harmony
  - tempo
  - metadata
#  - custom.themeA
  - composer
  - custom.librettist
  # - ambitus
  # - density
  # - texture     
  # - interval # to extract Melody_values task, both ambitus and interval are needed
  - key
  - lyrics

split_keywords:
  - woodwind
  - brass
  - wind
