data_dir: data
musescore_dir: data
metadata_dir: metadata
metadata_id_col: AriaId
intermediate_files_dir: intermediate
parallel: true
max_processes: 10
read_log:
  file_path: logs/read.log
  level: INFO
write_log:
  file_path: logs/write.log
  level: INFO
features:
  - core
  - custom.core_mscx
  - tempo
#  - custom.themeA
  - scoring
  - custom.file_name
  - scale
  - custom.scale_relative
  - ambitus
  - interval # to generate Melody_values reports, both ambitus and interval are needed
  # - density
  # - texture     
  # - custom.harmony
  - metadata
  - composer
  - custom.librettist
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
  - key
=======
  # - key
>>>>>>> 47933da (harmony fixings and report)
=======
  # - key
>>>>>>> 7892977 (harmony fixings and report)
=======
  - key
>>>>>>> 25e2c36 (Change directory new features and add tests)
  - lyrics
  - dynamics
  - rhythm

split_keywords:
  - woodwind
  - brass
  - wind