metadata_dir: ./metadata
metadata_id_col: AriaId
data_dir: arias
musescore_dir:
expand_repeats: false
parallel: false
max_processes: 8
log:
  file_path: logs/musif.log
  file_level: DEBUG
  console_level: INFO
features:
  - scoring
  - file_name
  - metadata
  - core
  - composer
  - librettist
  - key
  - tempo
  - ambitus
  - interval
  # - density
  # - texture
  - themeA
  - harmony
  # - lyrics
  # - scale
#  - scale_relative
  # - dynamics
split_keywords:  # Used to split the possible layers present depending on the instrument name
  - woodwind
  - brass
  - wind
parts_filter:
  - vnI
  - obI
  - ten
  # - vnII
  # - va
  # - bs
  # - sop
  # - alt
  # - bar
  # - bass
  # - bbar
