internal_data_dir: ./internal_data
metadata_dir: ./metadata
metadata_id_col: AriaId
data_dir: arias/prueba
musescore_dir:
expand_repeats: true
parallel: false
max_processes: 8
read_log:
  file_path: logs/read.log
  file_level: DEBUG
  console_level: INFO
write_log:
  file_path: logs/write.log
  file_level: WARNING
  console_level: INFO
features:
  - core
  - tempo
#  - themeA
  - scoring
  - file_name
  - scale
  - scale_relative
  - ambitus
  - interval # to generate Melody_values reports, both ambitus and interval are needed
  # - density
  # - texture     
  - harmony
  - metadata
  - composer
  - librettist
  - key
  - lyrics
  - dynamics
  - rhythm

split_keywords:  # Used to split the possible layers present depending on the instrument name
  - woodwind
  - brass

  - wind
parts_filter:
  - vnI
  # - vnII
  - obI
  # - va
  # - bs
  # - sop
  - ten
  # - alt
  # - bar
  # - bass
  # - bbar
