data_dir: ../data
metadata_dir: metadata
metadata_id_col: AriaId
intermediate_files_dir: intermediate
parallel: true
max_processes: 10
log:
  file_path: logs/read.log
  level: INFO
features:
  - file_name
  - librettist
  - harmony
  - ambitus
  - density
  - interval # to extract Melody_values task, both ambitus and interval are needed
  - key
  - lyrics
  - prefix
  - scale
  - scoring
  - tempo
  - composer
split_keywords:
  - woodwind
  - brass
  - wind
