data_dir: ../data
metadata_dir: ../metadata
metadata_id_col: AriaId
parallel: false
max_processes: 8
read_log:
  file_path: logs/read.log
  level: WARNING
write_log:
  file_path: logs/write.log
  level: DEBUG
features:
  - scoring
  - file_name
  - metadata
  - themeA
  - core
  - composer
  - librettist
  - ambitus
  - interval
  - tempo
  - density
#  - texture
  - harmony
  - lyrics
  - scale
#  - scale_relative
  - key
  - dynamics
split_keywords:  # Used to split the possible layers present depending on the instrument name
  - woodwind
  - brass
  - wind
