metadata_dir: ../metadata
metadata_id_col: AriaId
data_dir: ../../Corpus/xml
musescore_dir: ../../Corpus/musescore
expand_repeats: false
parallel: true
max_processes: 8
read_log:
  file_path: logs/read.log
  file_level: DEBUG
  console_level: WARNING
write_log:
  file_path: logs/write.log
  file_level: WARNING
  console_level: INFO
features:
  - scoring
  - file_name
  - metadata
  - themeA
  - core
  - composer
  - librettist
  - ambitus
  - interval
  - tempo
  - density
#  - texture
  - harmony
  - lyrics
  - scale
#  - scale_relative
  - key
  - dynamics
split_keywords:  # Used to split the possible layers present depending on the instrument name
  - woodwind
  - brass
  - wind
parts_filter:
  - vnI
  - vnII
  - va
  - bs
  - sop
  - ten
  - alt
  - bar
  - bass
  - bbar
