arias_scoring_file_path: "G:\\.shortcut-targets-by-id\\1_cjGg4wtpwon9Q16G4tndJVUqWzXGz4n\\DidonERC\\Investigacion DIDONE\\_Ana\\Music Analysis\\Arias_scoring.xlsx"
characters_gender_file_path: "G:\\.shortcut-targets-by-id\\1_cjGg4wtpwon9Q16G4tndJVUqWzXGz4n\\DidonERC\\Investigacion DIDONE\\_Ana\\Music Analysis\\Groupings\\Characters gender.xlsx"
arias_clefs_file_path: "G:\\.shortcut-targets-by-id\\1_cjGg4wtpwon9Q16G4tndJVUqWzXGz4n\\DidonERC\\Investigacion DIDONE\\_Ana\\Music Analysis\\Arias_clefs.xlsx"
metadata_dir: metadata
metadata_id_col: FileName
read_log:
  file_path: logs/read.log
  level: ERROR
write_log:
  file_path: logs/write.log
  level: INFO
parallel: true
features:
  - melodic
#  - harmonic
#  - texture
split_keywords:
  - woodwind
  - brass
  - wind
