arias_scoring_file: data/arias_scoring.xlsx
characters_gender_file: data/characters_gender.xlsx
arias_clefs_file: data/arias_clefs.xlsx
instruments_abbreviations_file: data/instruments_abbreviations.json
instruments_families_file: data/instruments_families.json
families_abbreviations_file: data/families_abbreviations.json
translations_file: data/translations.json
intermediate_files_dir: intermediatea
logs_dir: logs
log_level: DEBUG
sequential: false
features:
  - melodic
#  - harmonic
#  - texture
split: false
